/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formas_Recepcion;

import Metodos_Configuraciones.metodosDatosBasicos;
import java.awt.Color;
import java.sql.Connection;
import java.text.DecimalFormat;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Cronos
 */
public class jdDividirEnvio extends javax.swing.JDialog {

    /**
     * Creates new form jdDividirEnvio
     */
    DefaultTableModel modelo;
    jdBoletaSalidaReceptor jdB;
    metodosDatosBasicos mdb;
    Connection cn;

    public jdDividirEnvio(java.awt.Frame parent, boolean modal, String sacos, String kilos, String Idioma, Connection cn) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        this.cn = cn;
        mdb = new metodosDatosBasicos(cn, Idioma);

        lblSacosTotales.setText(sacos);
        lblKilosTotales.setText(kilos);
        modelo = (DefaultTableModel) tablaDivisiones.getModel();
    }

    public void calcular() {

        try {
            limpiar(tablaDivisiones);
            DecimalFormat formato = new DecimalFormat("#.00");

            double kilosDisponibles = Double.parseDouble(lblKilosTotales.getText());
            int sacosDisponibles = Integer.parseInt(lblSacosTotales.getText());

            sacosDisponibles = sacosDisponibles / Integer.parseInt(jTextField1.getText());
            kilosDisponibles = kilosDisponibles / Double.parseDouble(jTextField1.getText());

            int valorCalculado = 0;

            if (!jTextField1.getText().equals(" ") || !jTextField1.getText().equals("0")) {
                int numDiv = Integer.parseInt(jTextField1.getText());
                for (int i = 0; i < numDiv; i++) {
                    modelo.addRow(new Object[]{i + 1, sacosDisponibles, formato.format(kilosDisponibles)});
                    valorCalculado = valorCalculado + Integer.parseInt(tablaDivisiones.getValueAt(i, 1) + "");
                    //sacos = sacos + Integer.parseInt(tablaDivisiones.getValueAt(i, 1) + "");
                    //kilos = kilos + Integer.parseInt(tablaDivisiones.getValueAt(i, 2) + "");
                }
            }

            valorCalculado = Integer.parseInt(lblSacosTotales.getText()) - valorCalculado;
            valorCalculado = valorCalculado + Integer.parseInt(modelo.getValueAt(0, 1) + "");
            modelo.setValueAt(valorCalculado, 0, 1);

            sumar();
            setBox(tablaDivisiones, tablaDivisiones.getColumnModel().getColumn(3));

        } catch (Exception e) {

        }

    }

    public void setBox(JTable tabla, TableColumn columna) {
        String[] datos = mdb.cargarCombos("select concat(responsable,', ',nombre,', ',placas) from vehiculo").split("¬");
        JComboBox c = new JComboBox((Object[]) datos);

        columna.setCellEditor(new DefaultCellEditor(c));
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        columna.setCellRenderer(renderer);

    }

    public void sumar() {
        DecimalFormat formato = new DecimalFormat("#.00");
        int sacos = 0;
        double kilos = 0;

        for (int i = 0; i < modelo.getRowCount(); i++) {
            sacos = sacos + Integer.parseInt(modelo.getValueAt(i, 1) + "");
            kilos = kilos + Double.parseDouble(modelo.getValueAt(i, 2) + "");
        }

        jLabel6.setText(sacos + "");
        jLabel7.setText(formato.format(kilos) + "");

        if (kilos > Double.parseDouble(lblKilosTotales.getText())) {
            jLabel7.setForeground(Color.red);
        } else {
            jLabel7.setForeground(Color.BLACK);
        }

        if (sacos > Integer.parseInt(lblSacosTotales.getText())) {
            jLabel6.setForeground(Color.red);
        } else {
            jLabel6.setForeground(Color.BLACK);
        }
    }

    private void limpiar(JTable tabla) {
        while (tabla.getRowCount() > 0) {
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDivisiones = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblSacosTotales = new javax.swing.JLabel();
        lblKilosTotales = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dividir Envio");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Kilos disponibles");

        tablaDivisiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Sacos", "Kilos", "Transporte"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDivisiones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaDivisionesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablaDivisiones);
        if (tablaDivisiones.getColumnModel().getColumnCount() > 0) {
            tablaDivisiones.getColumnModel().getColumn(0).setMinWidth(50);
            tablaDivisiones.getColumnModel().getColumn(0).setPreferredWidth(50);
            tablaDivisiones.getColumnModel().getColumn(0).setMaxWidth(50);
            tablaDivisiones.getColumnModel().getColumn(1).setMinWidth(100);
            tablaDivisiones.getColumnModel().getColumn(1).setPreferredWidth(100);
            tablaDivisiones.getColumnModel().getColumn(1).setMaxWidth(100);
            tablaDivisiones.getColumnModel().getColumn(2).setMinWidth(100);
            tablaDivisiones.getColumnModel().getColumn(2).setPreferredWidth(100);
            tablaDivisiones.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        jLabel2.setText("Sacos Disponibles");

        lblSacosTotales.setText("13");

        lblKilosTotales.setText("148");

        jLabel3.setText("Numero Divisiones");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jLabel4.setText("Kilos Totales");

        jLabel5.setText("Sacos Totales");

        jLabel6.setText("-");

        jLabel7.setText("-");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKilosTotales)
                                    .addComponent(lblSacosTotales)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblSacosTotales))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblKilosTotales))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        calcular();
    }//GEN-LAST:event_jTextField1KeyReleased

    private void tablaDivisionesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaDivisionesKeyReleased
        // TODO add your handling code here:
        sumar();
    }//GEN-LAST:event_tablaDivisionesKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int contador = 0;
        for (int i = 0; i < tablaDivisiones.getRowCount(); i++) {
            String valor = tablaDivisiones.getValueAt(i, 3) + "";
            //JOptionPane.showMessageDialog(null, "Valor " + valor);
            if (valor.equals("null") || valor.equals("Seleccione")) {
                contador = contador + 1;
            }
        }

        if (contador == 0) {
            jdB.insertarBoletaDivision(modelo);
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona Transporte");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdDividirEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdDividirEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdDividirEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdDividirEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
 /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdDividirEnvio dialog = new jdDividirEnvio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblKilosTotales;
    private javax.swing.JLabel lblSacosTotales;
    private javax.swing.JTable tablaDivisiones;
    // End of variables declaration//GEN-END:variables
}
