/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formas_Sociedades;

import Idioma.Propiedades;
import Metodos_Configuraciones.metodosDatosBasicos;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class jdPrecioCafeSociedad extends javax.swing.JDialog {

    /**
     * Creates new form jdPrecioCafeSociedad
     */
    Connection cn;
    metodosDatosBasicos mdb;
    DefaultTableModel modelo;
    String claveSociedad, Idioma;
    Propiedades idioma;

    public jdPrecioCafeSociedad(java.awt.Frame parent, boolean modal, String claveSociedad, String Idioma, Connection cn) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        this.cn = cn;
        this.Idioma = Idioma;
        idioma = new Propiedades(Idioma);
        mdb = new metodosDatosBasicos(cn, Idioma);
        this.claveSociedad = claveSociedad;
        modelo = (DefaultTableModel) jTable1.getModel();

        rellenarCombos();
        llenarTabla();
        traductor();
    }

    public void traductor() {
        jLabel5.setText(idioma.getProperty("Clave"));
        jLabel6.setText(idioma.getProperty("NombreCorto"));
        jLabel7.setText(idioma.getProperty("IdentificacionFiscal"));
        jLabel1.setText(idioma.getProperty("FormaDeCafe"));
        jLabel2.setText(idioma.getProperty("Retencion"));
        jLabel3.setText(idioma.getProperty("PrecioKilo"));
        jLabel4.setText(idioma.getProperty("CentavosKilo"));

        jTable1.getColumnModel().getColumn(0).setHeaderValue(idioma.getProperty("FormaDeCafe"));
        jTable1.getColumnModel().getColumn(1).setHeaderValue(idioma.getProperty("PrecioKilo"));
        jTable1.getColumnModel().getColumn(2).setHeaderValue(idioma.getProperty("Retencion"));
        jTable1.getColumnModel().getColumn(3).setHeaderValue(idioma.getProperty("CentavosKilo"));

        jButton1.setText(idioma.getProperty("Anadir"));
        jButton2.setText(idioma.getProperty("Modificar"));
        jButton3.setText(idioma.getProperty("VerHistorial"));
        jButton4.setText(idioma.getProperty("Eliminar"));
    }

    public void rellenarCombos() {

        String[] datos1 = mdb.cargarCombos("select descripcion from formacafe").split("¬");
        comboForma.setModel(new DefaultComboBoxModel((Object[]) datos1));

        String[] datos2 = mdb.cargarCombos("select descripcion from retenciones").split("¬");
        comboRetencion.setModel(new DefaultComboBoxModel((Object[]) datos2));

        String[] datos3 = mdb.devolverLineaDatos("select razonsocial, nombrecorto, identificacionfiscal from personam where clavecorte='" + claveSociedad + "'", 3).split("¬");

        lblSociedad.setText(datos3[0]);
        lblNC.setText(datos3[1]);
        lblRFC.setText(datos3[2]);
    }

    public void llenarTabla() {
        limpiar(jTable1);
        String idSociedad = mdb.devuelveId("select id from personam where razonsocial='" + lblSociedad.getText() + "'");
        mdb.cargarInformacion2(modelo, 4, "select f.Descripcion, precioKg, r.Descripcion, r.importe\n"
                + "from preciocafesociedad p\n"
                + "inner join formacafe f on (p.id_formaCafe=f.ID)\n"
                + "inner join retenciones r on(p.id_Retencion=r.ID) "
                + "where p.id_sociedad=" + idSociedad + "");
    }

    private void limpiar(JTable tabla) {
        while (tabla.getRowCount() > 0) {
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        comboForma = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        comboRetencion = new javax.swing.JComboBox<>();
        txtPrecioKg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCentavos = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblSociedad = new javax.swing.JLabel();
        lblNC = new javax.swing.JLabel();
        lblRFC = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Precio De Café Por Sociedad");
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Forma de Café", "Precio Kg", "Retención", "Centavos x Kg"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Forma Café");

        comboForma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Retención");

        comboRetencion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboRetencion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboRetencionItemStateChanged(evt);
            }
        });

        txtPrecioKg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecioKgKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKgKeyTyped(evt);
            }
        });

        jLabel3.setText("Precio Kg");

        jLabel4.setText("Centavos x Kg");

        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Sociedad");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Nombre Corto");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Identificacion Fiscal");

        lblSociedad.setText("jLabel8");

        lblNC.setText("jLabel8");

        lblRFC.setText("jLabel8");

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ver Historal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(comboForma, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboRetencion, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtPrecioKg, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCentavos, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(lblSociedad))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(lblNC))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRFC)
                            .addComponent(jLabel7)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSociedad)
                    .addComponent(lblNC)
                    .addComponent(lblRFC))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboRetencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecioKg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCentavos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jButton4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboRetencionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboRetencionItemStateChanged
        // TODO add your handling code here:
        txtCentavos.setText(mdb.devuelveUnDato("select importe from retenciones where descripcion='" + comboRetencion.getSelectedItem() + "'"));
    }//GEN-LAST:event_comboRetencionItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String idForma = mdb.devuelveId("select id from formacafe where descripcion='" + comboForma.getSelectedItem() + "' ");
        String idRetencion = mdb.devuelveId("select id from retenciones where descripcion='" + comboRetencion.getSelectedItem() + "' ");
        String idSociedad = mdb.devuelveId("select id from personam where clavecorte='" + claveSociedad + "'");

        Date date = new Date();
        String fechaActual = new SimpleDateFormat("yyyy-MM-dd").format(date);

        DateFormat hourFormat = new SimpleDateFormat("HH:mm:ss");
        String horaActual = hourFormat.format(date);

        if (mdb.insertarBasicosComprobacion("insert into preciocafesociedad values (null, " + idSociedad + ", " + idForma + ", " + idRetencion + ", '" + txtPrecioKg.getText() + "' )")) {
            mdb.insertarBasicos("insert into historialPrecioCafeSociedad values( null, " + idSociedad + ", " + idForma + ", "
                    + "" + idRetencion + ", '" + txtPrecioKg.getText() + "', 'Usuario Modificacion', '" + fechaActual + "', '" + horaActual + "'  )");
        } else {
            JOptionPane.showMessageDialog(null, "Error, Verificar.");
        }
        llenarTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPrecioKgKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKgKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtPrecioKgKeyReleased

    private void txtPrecioKgKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKgKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioKgKeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        String formaCafe = jTable1.getValueAt(jTable1.getSelectedRow(), 0) + "";
        String precioKg = jTable1.getValueAt(jTable1.getSelectedRow(), 1) + "";
        String retencion = jTable1.getValueAt(jTable1.getSelectedRow(), 2) + "";
        String centavos = jTable1.getValueAt(jTable1.getSelectedRow(), 3) + "";

        comboForma.setSelectedItem(formaCafe);
        comboRetencion.setSelectedItem(retencion);
        txtPrecioKg.setText(precioKg);
        txtCentavos.setText(centavos);

        //JOptionPane.showMessageDialog(null, "Forma de Cafe: " + formaCafe);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        mdb.actualizarBasicos("update preciocafesociedad "
                + "set id_retencion=" + mdb.devuelveId("select id from retenciones where descripcion='" + comboRetencion.getSelectedItem() + "' ") + ", "
                + "precioKg=" + txtPrecioKg.getText() + " "
                + "where id_sociedad=" + mdb.devuelveId("select id from personam where clavecorte='" + claveSociedad + "'") + " and id_formaCafe=" + mdb.devuelveId("select id from formacafe where descripcion='" + comboForma.getSelectedItem() + "' ") + " ");
        llenarTabla();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        mdb.actualizarBasicos("delete from preciocafesociedad "
                + "where id_sociedad=" + mdb.devuelveId("select id from personam where clavecorte='" + claveSociedad + "'") + " and id_formaCafe=" + mdb.devuelveId("select id from formacafe where descripcion='" + comboForma.getSelectedItem() + "' ") + " ");
        llenarTabla();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdPrecioCafeSociedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdPrecioCafeSociedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdPrecioCafeSociedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdPrecioCafeSociedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
 /*    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdPrecioCafeSociedad dialog = new jdPrecioCafeSociedad(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboForma;
    private javax.swing.JComboBox<String> comboRetencion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblNC;
    private javax.swing.JLabel lblRFC;
    private javax.swing.JLabel lblSociedad;
    private javax.swing.JTextField txtCentavos;
    private javax.swing.JTextField txtPrecioKg;
    // End of variables declaration//GEN-END:variables
}
