/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formas_laboratorio;

import Idioma.Propiedades;
import Metodos_Configuraciones.metodosLaboratorio;
import com.toedter.calendar.JDateChooser;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Contador
 */
public class jpRecibirMuestras extends javax.swing.JPanel {
Connection cn;
    metodosLaboratorio mdb;
    DefaultTableModel modelo, modelo2;
      Propiedades idioma;
    String Idioma;
      JdNmuestra jdn;
    /**
     * Creates new form jpRecibirMuestras
     */
    public jpRecibirMuestras(Connection c, String Idioma) {
        initComponents();
        cn = c;
         this.Idioma=Idioma;
        mdb = new metodosLaboratorio(cn,Idioma);
        modelo = (DefaultTableModel) tablaM.getModel();
         modelo2 = (DefaultTableModel) tablaM1.getModel();
        llenarTabla();
        tablaM.setRowSorter(new TableRowSorter(modelo));
        tablaM1.setRowSorter(new TableRowSorter(modelo2));
        jButton2.setEnabled(false);
        idioma = new Propiedades(Idioma);
        
         jButton1.setText(idioma.getProperty("RecibirMuestra"));
        jButton2.setText(idioma.getProperty("RecibirMuestra"));
        
        tablaM.getColumnModel().getColumn(0).setHeaderValue(idioma.getProperty("Proceso"));
        tablaM.getColumnModel().getColumn(1).setHeaderValue(idioma.getProperty("Forma"));
        tablaM.getColumnModel().getColumn(2).setHeaderValue(idioma.getProperty("Beneficio"));
        tablaM.getColumnModel().getColumn(3).setHeaderValue(idioma.getProperty("Dueño"));
        tablaM.getColumnModel().getColumn(4).setHeaderValue(idioma.getProperty("Sublote"));
        tablaM.getColumnModel().getColumn(5).setHeaderValue(idioma.getProperty("Certificion"));
        tablaM.getColumnModel().getColumn(6).setHeaderValue(idioma.getProperty("Peso"));
        tablaM.getColumnModel().getColumn(7).setHeaderValue(idioma.getProperty("Sacos"));
        tablaM.getColumnModel().getColumn(8).setHeaderValue(idioma.getProperty("Comunidad"));
        tablaM.getColumnModel().getColumn(9).setHeaderValue(idioma.getProperty("MetodoSec"));
         tablaM1.getColumnModel().getColumn(0).setHeaderValue(idioma.getProperty("Proceso"));
        tablaM1.getColumnModel().getColumn(1).setHeaderValue(idioma.getProperty("Forma"));
        tablaM1.getColumnModel().getColumn(2).setHeaderValue(idioma.getProperty("Beneficio"));
        tablaM1.getColumnModel().getColumn(3).setHeaderValue(idioma.getProperty("Dueño"));
        tablaM1.getColumnModel().getColumn(4).setHeaderValue(idioma.getProperty("Sublote"));
        tablaM1.getColumnModel().getColumn(5).setHeaderValue(idioma.getProperty("Certificion"));
        tablaM1.getColumnModel().getColumn(6).setHeaderValue(idioma.getProperty("Peso"));
        tablaM1.getColumnModel().getColumn(7).setHeaderValue(idioma.getProperty("Sacos"));
        tablaM1.getColumnModel().getColumn(8).setHeaderValue(idioma.getProperty("Comunidad"));
        tablaM1.getColumnModel().getColumn(9).setHeaderValue(idioma.getProperty("MetodoSec"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        tablaM = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaM1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        tablaM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proceso", "Forma", "Beneficio", "Dueño", "#Sub Lote", "Certificacion", "Peso Kg", "# Sacos", "Comunidad", "Metodo secado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaM.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablaM);

        jButton1.setText("Recibir muestra");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Unificar Muestra");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tablaM1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proceso", "Forma", "Beneficio", "Dueño", "#Sub Lote", "Certificacion", "Peso Kg", "# Sacos", "Comunidad", "Metodo secado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaM1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaM1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaM1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tablaM1);

        jLabel1.setText("Muestas Recibidas:");

        jLabel2.setText("Muestras Registradas Manualmente:");

        jButton3.setText("Nueva");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Nuevo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(257, 257, 257)
                                .addComponent(jButton4)
                                .addGap(60, 60, 60)
                                .addComponent(jButton3)
                                .addGap(45, 45, 45)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane5))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
String dueño="",numsublote="",beneficio="",idlote="";
    private void tablaMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMMouseClicked
        beneficio = tablaM.getValueAt(tablaM.getSelectedRow(), 2) + "";
        dueño = tablaM.getValueAt(tablaM.getSelectedRow(), 3) + "";
        numsublote = tablaM.getValueAt(tablaM.getSelectedRow(), 4) + "";
   idlote=mdb.devuelveUnDato("select idlote from muestrasenviadas where dueño='"+dueño+"' and beneficio='"+beneficio+"' and lote='"+numsublote+"' ");
        
llenarTabla2();
 jButton2.setEnabled(false);

    }//GEN-LAST:event_tablaMMouseClicked
public void llenarTabla() {
        limpiar(tablaM);
      
        mdb.cargarInformacion2(modelo, 10, "SELECT`tipocafe`, `forma`, `beneficio`, `dueño`, `lote`,`certificado`, `peso`, `sacos`, `comunidad`,`Metodosecado`FROM muestrasenviadas;");
    
}
public void llenarTabla2() {
        limpiar(tablaM1);
      
        mdb.cargarInformacion2(modelo2, 10, "SELECT`tipocafe`, `forma`, `beneficio`, `dueño`,  `lote`,`certificado`, `peso`, `sacos`, `comunidad`,`Metodosecado`FROM bitacoralab where idlote=''and beneficio like'"+beneficio+"' and lote like'"+numsublote+"' and dueño like'"+dueño+"' ;");
    String a="";
   a= mdb.devuelveUnDato("SELECT `lote` FROM bitacoralab where idlote=''and beneficio like'"+beneficio+"' and lote like'"+numsublote+"' and dueño like'"+dueño+"' ;");
        if (!a.equals("")) {
            System.out.println("jalo");
             jButton1.setEnabled(false); 
    }else {
             jButton1.setEnabled(true); 
             System.out.println("jalon't");
        }
}
 private void limpiar(JTable tabla) {
        while (tabla.getRowCount() > 0) {
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 recibir();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   unificar();     // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
String dueño2="",numsublote2="",beneficio2="",id="", id2="";
    private void tablaM1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaM1MouseClicked
       jButton2.setEnabled(true); 
        jButton1.setEnabled(false); 
beneficio2 = tablaM1.getValueAt(tablaM1.getSelectedRow(), 2) + "";
        dueño2 = tablaM1.getValueAt(tablaM1.getSelectedRow(), 3) + "";
        numsublote2 = tablaM1.getValueAt(tablaM1.getSelectedRow(), 4) + "";
   id=mdb.devuelveUnDato("select id_bitacora from bitacoralab where dueño='"+dueño2+"' and beneficio='"+beneficio2+"' and lote='"+numsublote2+"' and idlote='' ");// TODO add your handling code here:
   id2=mdb.devuelveUnDato("select id_muestrasE from muestrasenviadas where dueño='"+dueño+"' and beneficio='"+beneficio+"' and lote='"+numsublote+"' ");
    }//GEN-LAST:event_tablaM1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jdn = new JdNmuestra(null, true, cn,Idioma);
        jdn.jpna = this;
        jdn.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jdNuevaMuestra jd = new jdNuevaMuestra(null,true);
        jd.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed
public void unificar(){
    mdb.actualizarBasicos("update bitacoralab set idlote='"+idlote+"' where id_bitacora="+id+";");
    mdb.eliminardato("DELETE FROM muestrasenviadas WHERE id_muestrasE="+id2+";");
     JOptionPane.showMessageDialog(null, "se ha unificado la informacion");
     llenarTabla();
     limpiar(tablaM1);
}
    public void recibir(){
    String fecha="";
     String[] datos = mdb.devuelveUnRow("select * from muestrasenviadas where idlote='"+idlote+"'",23).split(",");
     for (int i = 0; i < 23; i++) {
         System.out.println(datos[i]+"   '"+i+"'");
        
    }
     JDateChooser jd = new JDateChooser();
String message ="Escoge una fecha de llegada:\n";
Object[] params = {message,jd};
JOptionPane.showConfirmDialog(null,params,"Fecha de llegada", JOptionPane.PLAIN_MESSAGE);
SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
fecha=sdf.format(((JDateChooser)params[1]).getDate());
     int csm;
        if (mdb.devuelveUnDato("select id_muestra from bitacoralab order by id_muestra desc limit 1").equals("")) {
            csm=1;
        }else { csm = Integer.parseInt(mdb.devuelveUnDato("select id_muestra from bitacoralab order by id_muestra desc limit 1"));
        csm = csm + 1;}  
     mdb.insertarBasicos("insert into bitacoralab (id_bitacora,id_muestra,fecha_llegada,tipocafe,forma,beneficio,dueño,"
                                                                + "lote,peso,sacos,comunidad,estatus,taza,aspecto,mezasig,Metodosecado,calidadcereza,pesomuestra,ubicacioncafe"
                                                                + ",nomlote,predio,productor,fechalote,terminosecado,tomademuestra,fechacosecha,tomadapor,recibidapor,transportadapor,"
                                                                + "certificado,idlote) values(null," + csm + ",'" + fecha + "','" + datos[2] + "','" + datos[3] + "',"
                                                                + "'" + datos[4] + "','" + dueño + "','" + datos[6] + "','" + datos[7]+ "'"
                                                                + ",'" + datos[8] + "','" + datos[9] + "','L','0','0','0','" + datos[11] + "','" + datos[12] + ""
                                                                + "','" + datos[13] + "','" + datos[14] + "','',''"
                                                                + ",'','" + datos[15] + "','" + datos[16] + "','" + datos[17] + "','" + datos[18] + "','" + datos[19] + "','" + datos[20] + "','" + datos[21] + "','" + datos[22] + "','" + datos[1] + "')");
mdb.eliminardato("DELETE FROM muestrasenviadas WHERE id_muestrasE="+datos[0]+";");
 JOptionPane.showMessageDialog(null, "se ha recibido la muestra");
llenarTabla();
 
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tablaM;
    private javax.swing.JTable tablaM1;
    // End of variables declaration//GEN-END:variables
}
