/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formas_LaboratorioN;

import Visual.Visual;
import com.spire.xls.Workbook;
import com.spire.xls.Worksheet;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author usuario
 */
public class Barra_progreso extends javax.swing.JFrame {

    /**
     * Creates new form Barra_progreso
     */
    private Timer t;
    private final ActionListener ac;
    int x = 0;

    public Barra_progreso() {
        initComponents();
        this.setLocationRelativeTo(null);
        setBackground(new Color(0,0,0,10));
        jLabel1.setBackground(Color.LIGHT_GRAY);

        ac = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                x = x + 1;
                jProgressBar1.setValue(x);

                if (jProgressBar1.getValue() == 1) {
                    jLabel1.setText("Cargando Reporte..");

                }

                if (jProgressBar1.getValue() == 25) {
                    jLabel1.setText("Cargando Datos..");

                }

                if (jProgressBar1.getValue() == 50) {
                    jLabel1.setText("Creando Graficos..");

                }

                if (jProgressBar1.getValue() == 75) {
                    jLabel1.setText("Un poco más..");

                    // Cargar documento de Excel
                    Workbook wb = new Workbook();
                    wb.loadFromFile("C:\\fincalab\\reporteLaboratorio.xlsx");

                    // Obtenga la segunda hoja de trabajo
                    Worksheet sheet = wb.getWorksheets().get(0);

                    // Método de llamada para guardar en formato PDF
                    sheet.saveToPdf("C:\\fincalab\\ReporteIndividual.pdf");

                    Visual v = new Visual("C:\\fincalab\\ReporteIndividual.pdf");
                    v.setVisible(true);
                }

                if (jProgressBar1.getValue() == 100) {
                    dispose();
                    t.stop();
                }

            }

        };

        t = new Timer(100, ac);
        t.start();

        //hilo();
    }

    public void hilo() {

        t = new Timer(100, ac);
        t.start();

        x = x + 1;
        jProgressBar1.setValue(x);

        if (jProgressBar1.getValue() == 1) {
            jLabel1.setText("Cargando Reporte..");

        }

        if (jProgressBar1.getValue() == 25) {
            jLabel1.setText("Cargando Datos..");

        }

        if (jProgressBar1.getValue() == 50) {
            jLabel1.setText("Creando Graficos..");

        }

        if (jProgressBar1.getValue() == 75) {
            jLabel1.setText("Un poco más..");

            // Cargar documento de Excel
            Workbook wb = new Workbook();
            wb.loadFromFile("C:\\fincalab\\reporteLaboratorio.xlsx");

            // Obtenga la segunda hoja de trabajo
            Worksheet sheet = wb.getWorksheets().get(0);

            // Método de llamada para guardar en formato PDF
            sheet.saveToPdf("C:\\fincalab\\ReporteIndividual.pdf");

            Visual v = new Visual("C:\\fincalab\\ReporteIndividual.pdf");
            v.setVisible(true);
        }

        if (jProgressBar1.getValue() == 100) {
            dispose();
            t.stop();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cargando..");
        setEnabled(false);
        setUndecorated(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("-");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barra_progreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barra_progreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barra_progreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barra_progreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barra_progreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
