/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formas_Configuraciones_Recepcion;

import Metodos_Configuraciones.metodosDatosBasicos;
import Metodos_Configuraciones.validaConfi;
import java.sql.Connection;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos Valdez
 */
public class jdFactorForma extends javax.swing.JDialog {

    /**
     * Creates new form jdPais
     */
    String tipo, ID_Forma1C, ID_Forma2C;
    String ID_Forma2, Formula, ID_Forma1, Factor, Porcentaje;
    Connection cn;
    jpFactorForma jp;
    validaConfi valiConf;
    metodosDatosBasicos mdb;

    public jdFactorForma(java.awt.Frame parent, boolean modal, String tipo, String ID_Forma1C, String ID_Forma2C, String FormulaC, String FactorC, String PorcentajeC, Connection c) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        this.tipo = tipo;
        this.ID_Forma1C = ID_Forma1C;
        this.ID_Forma2C = ID_Forma2C;
        cn = c;
        valiConf = new validaConfi();
        mdb = new metodosDatosBasicos(cn, "");

        if (tipo.equals("1")) {
            setTitle("Nuevo Factor Forma");
        } else {
            setTitle("Editar Factor Forma");
            txtForm.setText(FormulaC);
            txtFactor.setText(FactorC);
            txtPorcentaje.setText(PorcentajeC);
        }

        rellenarCombos();
    }

    public void rellenarCombos() {
        String[] datos;
        datos = mdb.cargarCombos("SELECT descripcion from formacafe").split(",");
        comboForma1.setModel(new DefaultComboBoxModel((Object[]) datos));
        comboForma2.setModel(new DefaultComboBoxModel((Object[]) datos));
    }

    public void tipoProceso() {
        try {
            String sql = "";

            Formula = txtForm.getText();
            ID_Forma2 = comboForma2.getSelectedItem() + "";
            ID_Forma1 = comboForma1.getSelectedItem() + "";
            Formula = txtForm.getText();
            Factor = txtFactor.getText();
            Porcentaje = txtPorcentaje.getText();

            if (tipo.equals("1")) {
                //nuevoPais();
                sql = "INSERT INTO FactorForma VALUES(null,'" + mdb.devuelveId("select id from formacafe where descripcion='" + ID_Forma1 + "'") + "','"
                        + mdb.devuelveId("select id from formacafe where descripcion='" + ID_Forma2 + "'") + "','"
                        + Formula + "','" + Factor + "','" + Porcentaje + "', 1, 1,current_date()"
                        + ", current_time(),1,1,1,1)";
                System.out.println(sql);
                mdb.insertarBasicos(sql);
                jp.llenaTabla();
                this.dispose();
            } else {
                //editarPais();
                sql = "UPDATE FactorForma "
                        + "SET  ID_Forma1='" + mdb.devuelveId("select id from formacafe where descripcion='" + ID_Forma1 + "'") 
                        + "',Formula='" + Formula + "',ID_Forma2='" 
                        + mdb.devuelveId("select id from formacafe where descripcion='" + ID_Forma2 + "'") 
                        + "',Factor='" + Factor + "' "
                        + ",Porcentaje='" + Porcentaje 
                        + "'where ID_Forma1='" + mdb.devuelveId("select id from formacafe where descripcion='" + ID_Forma1C + "'") 
                        + "' AND ID_Forma2='" + mdb.devuelveId("select id from formacafe where descripcion='" + ID_Forma2C + "'") + "' ";
                System.out.print(sql);
                mdb.actualizarBasicos(sql);
                jp.llenaTabla();
                this.dispose();

            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtForm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFactor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPorcentaje = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboForma1 = new javax.swing.JComboBox<>();
        comboForma2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Forma de Cafe 2");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Formula");

        txtForm.setEditable(false);
        txtForm.setEnabled(false);
        txtForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFormActionPerformed(evt);
            }
        });
        txtForm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFormKeyReleased(evt);
            }
        });

        jLabel3.setText("Forma de Cafe 1");

        txtFactor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFactorActionPerformed(evt);
            }
        });
        txtFactor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFactorKeyReleased(evt);
            }
        });

        jLabel4.setText("Factor");

        txtPorcentaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPorcentajeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPorcentajeKeyTyped(evt);
            }
        });

        jLabel5.setText("Porcentaje");

        comboForma2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboForma2ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                    .addComponent(txtForm)
                    .addComponent(txtFactor)
                    .addComponent(txtPorcentaje)
                    .addComponent(comboForma1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(comboForma2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboForma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboForma2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tipoProceso();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtFormKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFormKeyReleased
        // TODO add your handling code here:
        if (txtForm.getText().length() != 0) {
            txtForm.setText(valiConf.primerLetraMayuscula(txtForm.getText()).replace("S/n", "S/N"));
            txtForm.setText(valiConf.primerLetraMayuscula(txtForm.getText()).replace("S/d", "S/D"));
            txtForm.setText(valiConf.primerLetraMayuscula(txtForm.getText()).replace("S/o", "S/O"));
        }

    }//GEN-LAST:event_txtFormKeyReleased

    private void txtFactorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFactorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFactorActionPerformed

    private void txtFactorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFactorKeyReleased
        // TODO add your handling code here:
        if (txtFactor.getText().length() != 0) {
            txtFactor.setText(valiConf.primerLetraMayuscula(txtFactor.getText()).replace("S/n", "S/N"));
            txtFactor.setText(valiConf.primerLetraMayuscula(txtFactor.getText()).replace("S/d", "S/D"));
            txtFactor.setText(valiConf.primerLetraMayuscula(txtFactor.getText()).replace("S/o", "S/O"));
        }

    }//GEN-LAST:event_txtFactorKeyReleased

    private void txtPorcentajeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcentajeKeyReleased
        // TODO add your handling code here:
        if (txtPorcentaje.getText().length() != 0) {
            txtPorcentaje.setText(valiConf.primerLetraMayuscula(txtPorcentaje.getText()).replace("S/n", "S/N"));
            txtPorcentaje.setText(valiConf.primerLetraMayuscula(txtPorcentaje.getText()).replace("S/d", "S/D"));
            txtPorcentaje.setText(valiConf.primerLetraMayuscula(txtPorcentaje.getText()).replace("S/o", "S/O"));
        }

    }//GEN-LAST:event_txtPorcentajeKeyReleased

    private void txtPorcentajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcentajeKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtPorcentajeKeyTyped

    private void txtFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFormActionPerformed

    private void comboForma2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboForma2ItemStateChanged
        // TODO add your handling code here:
        ID_Forma2 = comboForma2.getSelectedItem() + "";
        ID_Forma1 = comboForma1.getSelectedItem() + "";
        txtForm.setText(ID_Forma1 + " / " + ID_Forma2);
    }//GEN-LAST:event_comboForma2ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the dialog */
 /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdPais dialog = new jdPais(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        //</editor-fold>

        /* Create and display the dialog */
 /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdPais dialog = new jdPais(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboForma1;
    private javax.swing.JComboBox<String> comboForma2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtFactor;
    private javax.swing.JTextField txtForm;
    private javax.swing.JTextField txtPorcentaje;
    // End of variables declaration//GEN-END:variables
}
