/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formas_Configuraciones_Recepcion;
import Idioma.Propiedades;
import Formas_Configuraciones_DatosBasicos.*;
import Metodos_Configuraciones.metodosDatosBasicos;
import java.sql.Connection;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos Valdez
 */
public class jpEvaluaciones extends javax.swing.JPanel {

    /**
     * Creates new form jpFCstado
     */
    jdFormaEvaluacion jdFE;
    Connection cn;
    metodosDatosBasicos mdb;
    DefaultTableModel modelo;
    Propiedades idioma;
    String Idioma;
    
    public jpEvaluaciones(Connection c, String Idioma) {
        initComponents();

        cn = c;
        mdb = new metodosDatosBasicos(cn, Idioma);
        idioma = new Propiedades(Idioma);
        this.Idioma=Idioma;
        
        jButton1.setText(idioma.getProperty("Cerrar"));
        jButton3.setText(idioma.getProperty("AgregarEvaluaciones"));
        
        llenarCombo();
    }

    public void llenarCombo() {
        String[] datos = mdb.cargarCombos("SELECT descripcion from formacafe").split("¬");
        comboFormas.setModel(new DefaultComboBoxModel((Object[]) datos));

        String forma = comboFormas.getSelectedItem() + "";
        txtAreaCombo.setText(mdb.cargarFormaProceso("select te.descripcion\n"
                + "from formaevaluacion fe\n"
                + "inner join formacafe fc on (fe.ID_Forma=fc.ID)\n"
                + "inner join tipoevaluacion te on (fe.ID_Evaluacion=te.ID) "
                + "where fc.descripcion ='" + forma + "'"
        ));
    }


    /* DefaultTableModel modelo = (DefaultTableModel) tablaReglas.getModel();
        for(int i=0; i>procesos.length; i++){
        modelo.addRow(new Object[]{"Prueba 1",true});
    
        }
     */
    //✘ ✓
    /*   public void construirTabla() {
        String[] columnas = mdb.cargarCombos("Select descripcion from procesocafe").split("¬");
        for (int i = 0; i < columnas.length; i++) {
            System.out.println(columnas[i]);
            //modelo.addColumn(new Object[]{columnas[i],true} );
            modelo.addColumn(columnas[i]);
            // modelo.addRow(new Object[]{"Prueba "+1, true, false, " ✓","✘","3","4","5","6","7","8","9","10","11","12"});
        }
        //modelo.addRow(new Object[]{"Cereza ", "✓", "✘", "✘", "✘", "✓", "✘", "✓"});
        //modelo.addRow(new Object[]{"Capulin ", "✓", "✘", "✘", "✘", "✓", "✓", "✘"});
        //modelo.addRow(new Object[]{"Pergamino ", "✓", "✘", "✓", "✓", "✘", "✓", "✓"});
        
    }
     */
 /* public void llenaTabla() {
        limpiar(tablaFormaCafe);
        String sql = "select clave, descripcion from formacafe where ID_Situacion=1";
        mdb.cargarInformacion2(modelo, 2, sql);
        String[] datos = mdb.cargarFormaProceso("SELECT fc.descripcion, GROUP_CONCAT(DISTINCT pc.Descripcion\n"
                + "					ORDER BY pc.Descripcion ASC\n"
                + "					SEPARATOR '-') AS \"Procesos\"\n"
                + " FROM formaproceso fp\n"
                + "	INNER JOIN formacafe fc on (fp.ID_Forma=fc.ID)\n"
                + "	INNER JOIN procesocafe pc on (fp.ID_Proceso=pc.ID)\n"
                + " GROUP BY fc.Descripcion").split("¬");
        for(int i=0; i<datos.length; i++){
            String[] dat = datos[i].split(",");
            String col1 = dat[0];
            String col2 = dat[1];
           
            modelo.addRow(new Object[]{col1,col2});
             
        //JOptionPane.showMessageDialog(this, datos[i]);
        }
    }*/

    private void limpiar(JTable tabla) {
        while (tabla.getRowCount() > 0) {
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        comboFormas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaCombo = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(1010, 700));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setPreferredSize(new java.awt.Dimension(830, 570));

        jButton3.setText("Agregar Evaluaciones");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        comboFormas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione.." }));
        comboFormas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFormasItemStateChanged(evt);
            }
        });

        txtAreaCombo.setEditable(false);
        txtAreaCombo.setColumns(20);
        txtAreaCombo.setRows(5);
        jScrollPane1.setViewportView(txtAreaCombo);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(comboFormas, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(comboFormas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
            jdFE = new jdFormaEvaluacion(null, true,"2",comboFormas.getSelectedItem()+"", Idioma,cn);
            jdFE.jpE = this;
            jdFE.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void comboFormasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFormasItemStateChanged
        // TODO add your handling code here:
        String forma = comboFormas.getSelectedItem() + "";
        txtAreaCombo.setText(mdb.cargarFormaProceso("select te.descripcion\n"
                + "from formaevaluacion fe\n"
                + "inner join formacafe fc on (fe.ID_Forma=fc.ID)\n"
                + "inner join tipoevaluacion te on (fe.ID_Evaluacion=te.ID) "
                + "where fc.descripcion ='" + forma + "'"));
    }//GEN-LAST:event_comboFormasItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.removeAll();
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboFormas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaCombo;
    // End of variables declaration//GEN-END:variables
}
